[package]
name = "word_counter_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1"
time = "0.3.30"
sysinfo = "0.29.10"

